### ISSUE TITLE
Kanon crashing on start-up

### ISSUE THREAD

**Issue by SanktyRG** [ajusa/VNDS-LOVE#19]
**Describe the bug**

I downloaded and even tried reconverting the novel from scratch but whenever I try to open it with VNDS-LOVE for Nintendo Switch, the app crashes, showing the error log.

**To Reproduce**
1. Download a copy of Kanon (either SD or HD), or try the original converter.
2. Copy the novel to the desired path on the SD card.
3. Open Homebrew Menu from an app by keeping R key pressed.
4. Open VNDS-LOVE homebrew and select Kanon novel to open.

**Expected behavior**
The novel booting normally, it is worth noting it works fine on both NDS and Android variants of the original VNDS.

**Desktop (please complete the following information):**
 - Nintendo Switch v11.0.1, Atmosphere 0.17.0.
 - Version of VNDS-LOVE: 0.0.6

**Additional context**
I just discovered your homebrew so I don't really understand the error, but will provide the crash log.

Here's the log file for the crash:
[crash.txt](https://github.com/ajusa/VNDS-LOVE/files/5778365/crash.txt)

**Comment by ajusa** [comment]
Hey, thanks for filing this bug report! I'm taking a look into this now. Is there a "log.txt" that was created in the same directory as the novels folder? If so, I would appreciate it if you could attach that.

**Comment by SanktyRG** [comment]
Hello and thank you for taking a look into this. There sure was a "log.txt", I will upload it for you now:

[log.txt](https://github.com/ajusa/VNDS-LOVE/files/5778526/log.txt)

**Comment by ajusa** [comment]
Alright, seems the issue is that while the audio is valid, the extension is .ogg despite it being a .wav file inside. For now, I've simply added better error handling for the audio files, and created a new pre-release so that you can actually get through some of the game.
[Removed]
Note that some audio will not work because of this change, but I'll try fixing it so that it can figure out which kind of audio it is. That'll probably take me a few days so I figured I would get out a release at least. I'll keep this issue open until that is actually done.
EDIT: Removed the release, it actually won't take me a few days to fix it, more like an hour. I'll update this issue once I've got it fixed.

**Comment by SanktyRG** [comment]
That's awesome news! Thank you very much for all the hard work. Glad it was something fixable, but to think a differently formatted audio file could cause so much trouble... Anyway, thanks again for this, will be awaiting the new release.

**Comment by ajusa** [comment]
No problem! I wasn't expecting this either, from my understanding the same person wrote the converter and the android version of VNDS, so they probably knew to code around it.
Hopefully closed with https://github.com/ajusa/VNDS-LOVE/commit/3d94dd5d525254e80cf4786eb8003b2c893ff01e. I only tested on my laptop, but that should fix the switch version as well.
Didn't take as long as I expected, thanks to there being a library someone else had written to figure out which format an audio file actually is. Here is the updated prerelease: https://github.com/ajusa/VNDS-LOVE/releases/tag/0.0.7
Feel free to reopen if there are still any issues!
