### ISSUE TITLE
Fast Forward/Skip Feature

### ISSUE THREAD

**Issue by poudink** [ajusa/VNDS-LOVE#21]
**Is your feature request related to a problem? Please describe.**
Missing feature from the original VNDS software.

**Describe the solution you'd like**
A fast forward button (this was mapped to the Y button on DS. In many visual novels on PC, this is mapped to ctrl) which quickly skips through text and a skip button (this was mapped to R+Y on DS) which instantly skips to the next choice.

**Comment by ajusa** [comment]
To clarify, holding down one button skips through text at a faster rate (like repeatedly pressing "a"). A different button skips directly to the next choice? The Y and R+Y make sense, and can be added for all gamepads (that way it includes the Switch).
Any ideas of what the default binding should be for PC for a skip button?

**Comment by poudink** [comment]
I haven't seen that many visual novels on PC with a skip button, but I know with Little Busters! it's numpad right/6.

**Comment by ajusa** [comment]
https://github.com/ajusa/VNDS-LOVE/commit/933857de470bccccd7f5365890dbd6bbb575d5b7 has a toggleable fast forward option that uses "y". The skip to next choice is a little more involved, since you basically want to skip while keeping track of the last background, foreground, and music that was playing until the choice. This is so that when the choice appears, the correct ambiance when selecting the choice.

**Comment by ajusa** [comment]
1fa3ffc binds "x" to skip to the next option. It tries to skip forward up to 10,000 lines to see whether or not a choice command appears. If there is no choice command, it doesn't try to skip. I won't be putting out a release until I've done some refactoring, [text.moon](https://github.com/ajusa/VNDS-LOVE/blob/master/src/text/text.moon) is starting to get pretty ugly and show signs of spaghetti code. Also https://github.com/ajusa/VNDS-LOVE/issues/30 still needs to be debugged before I'd feel comfortable putting out a release.
