### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by poudink** [ajusa/VNDS-LOVE#25]
**Is your feature request related to a problem? Please describe.**
Missing feature from the original VNDS software.

**Describe the solution you'd like**
If a ttf font is found in the visual novel's folder, use it instead of the default VNDS-LOVE font. The name of the font doesn't matter, as long as it's in the folder.

**Comment by ajusa** [comment]
Should be fixed with https://github.com/ajusa/VNDS-LOVE/commit/ddeb76a0d29dfd82dd99a5c350c4c91a8132dcbd
It does look... off? I prefer the normal font over the default.ttf that some of these novels provided. I'm planning to work on a config system as a part of #22, so I'll add an option to override the font with the system provided one that is used everywhere else.
I'll close this issue once that is done.
