### ISSUE TITLE
Saving/Loading

### ISSUE THREAD

**Issue by poudink** [ajusa/VNDS-LOVE#26]
**Is your feature request related to a problem? Please describe.**
Missing feature from the original VNDS software. The current implementation of saving and loading in VNDS-LOVE consists of saving to a single slot with X and automatic loading whenever a Visual Novel is close or launched.

**Describe the solution you'd like**
In the original VNDS software, automatic loading isn't present and it instead has to be done manually. I believe autoloads shouldn't be there in case someone wants to restart a visual novel with fresh data.
VNDS has eighteen save slots, or three pages with six slots each. Each save file is accompanied with a low res screenshot of the top screen, which equates to a screenshot of VNDS-LOVE without the text box. Having more slots than just eighteen would also be a welcome improvement.

**Comment by ajusa** [comment]
VNDS-LOVE has auto load, but not autosave (you have to hit X to save). Other than that, I agree/understand what you are suggesting. For now, I think I'll implement manual load/save with slots. 
Notes for myself/whoever implements it: The save preview can be done by looking at the loaded background and the images inside of the save. Draw those super scaled down inside of a box with the same aspect ratio as the background. Needs to gracefully handle both of those not existing though, just drawing a blank box if no preview could be found.

Each save should be named save0.json - saveX.json
This is a higher priority issue as breaking changes to save files should be done earlier rather than after people have existing saves that they can't port over without losing data.

I'd like to hear some ideas about the UI here though. Should people have to hit the start button to open a menu, select save, and then be able to view/load save slots? What should the interface look like for computers? Have a menu button that can open up the same menu, and then arrow keys/mouse for selecting things?

**Comment by poudink** [comment]
![Saving Interface](https://user-images.githubusercontent.com/29778535/103852492-f95fc480-5079-11eb-9274-3afde8197446.png)
This is the save file UI in VNDSx. It's entirely touch controlled. I'm thinking it'd probably be good to have something like this but mouse controlled. Enter would probably be the best key to use. In VNDSx, it's a button on the touch screen. You can also use X+R to open the saving menu and X+L to open the loading menu. The loading menu looks the same as the saving menu except the button next to the Cancel button says "Load" instead of "Save".

**Comment by poudink** [comment]
Forget what I said about entirely touch controlled, just remembered you could also use buttons to navigate. IIRC the D-Pad is used to select the save file, A is used to save and B is used to exit the menu.

**Comment by ajusa** [comment]
This should be finished with https://github.com/ajusa/VNDS-LOVE/commit/9119496132103715bce12386b8b949341958bf85!
Main deviations from VNDS: 
1. The preview doesn't include the foreground images. This would be a bit of a pain to implement, so I'm skipping it for now. My guess is that most people will be able to get by with just the background image (as it is super small anyway, so there wouldn't be detail). If someone in the future wants me to add this, feel free to make a separate issue.
2. Save slots are currently restricted to 10, but can easily be increased with a minor code change. 
3. There is no delete slot button. Not sure if the original VNDS had this (didn't see a delete button under the UI). To delete a save slot you basically just need to find the novel, find save[slot number].json, and delete it. Note that you can override save slots without any problems, but you can't clear them as of now.
4. Missing some of the keybindings that were mentioned. To save, you have to open the menu click save. I'm planning on redoing some of the input handling in the future, as it doesn't really support key combinations that well right now.
