### ISSUE TITLE
Game directory inside the VNDS-LOVE folder

### ISSUE THREAD

**Issue by ishani-rgb** [ajusa/VNDS-LOVE#34]
**Is your feature request related to a problem? Please describe.**
Not really,
It would be nice if we could just put the files into the directory where VNDS-Love is instead of appdata. I dont know whether this is already possible but I see no mention of it anywhere so.

**Describe the solution you'd like**
A directory in the root VNDS folder to put games into.

**Comment by ajusa** [comment]
Hello!

Unfortunately, this is not possible to do at this time. While I realize that it is inconvenient to move novels to appdata, this is a restriction of the framework that this project uses (LOVE2D). VNDS-LOVE is only allowed to write/read from the LOVE save directory, which is located inside of the appdata folder.

The only suggestion I can make is having a shortcut on your computer directly to the folder, so that you don't have to click to it directly all the time. Another option (which I haven't tried) is creating a symlink from the directory where VNDS-LOVE is to the appdata folder. https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/ might be a useful link to figure out how to do that.

Hope that helps!
