### ISSUE TITLE
Problem with "jump" function"

### ISSUE THREAD

**Issue by SanktyRG** [ajusa/VNDS-LOVE#35]
**Describe the bug**
I have a novel that stores strings for both a jump file (named RETFILE) and a jump label (named RETLABEL) so they can both be called later on with the "jump" structure `jump $RETFILE $RETLABEL`. The file is called correctly by the jump function but the label one is not working.

**To Reproduce**
1. On a main2.scr file we have:
`setvar RETFILE = "main2.scr"`
`setvar RETLABEL = "callret122"`
`jump 9020.scr`

On a 9029.scr file we have `jump $RETFILE $RETLABEL` but it only goes back to the start of "main2.scr".

**Expected behavior**
The jump function at the end of the "9020.scr" file should go back to the label "callret122" on "main2.scr" but doesn't so the novel stays in an infinite loop.

**Desktop (please complete the following information):**
 - I only tried Mac and Nintendo Switch, both with the same behavior.
 - Version of VNDS-LOVE: 0.0.11

**Additional context**
I will be uploading both "main2.scr" and "9020.scr" as TXT files:
[9020.txt](https://github.com/ajusa/VNDS-LOVE/files/6462437/9020.txt)
[main2.txt](https://github.com/ajusa/VNDS-LOVE/files/6462438/main2.txt)

Please attach a log file (located in the same directory as `novels`) if you can to help debug the issue. Thanks!

Here's the log: 
[log.txt](https://github.com/ajusa/VNDS-LOVE/files/6462433/log.txt)

Thanks in advance.

**Comment by ajusa** [comment]
Should be fixed with https://github.com/ajusa/VNDS-LOVE/commit/ef7bdba218c6295a1455ae47f30f8900ce28f759, please let me know if that isn't the case! I added an automated test for this use case, and tested the files you provided and they seem to run fine now.

Note that there will probably be other bugs like this related to text interpolation, the wiki on the specification isn't super clear/formal. When that happens just feel free to raise an issue with an example like this, it makes it super easy for me to debug and take a look.
